trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python312:
      python.version: '3.12'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: pip install -r hello_app/requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-cov
    pytest --cov=your_package_name tests/
  displayName: 'Run tests with coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  condition: succeededOrFailed()