trigger:
- main  # Or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

- script: python -m pip install --upgrade pip
- script: |
    find . -name "requirements.txt"

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-cov
    pytest --cov=your_package_name tests/
  displayName: 'Run tests with coverage'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  condition: succeededOrFailed()
