trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python312:
      python.version: '3.12'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- script: |
    pip install -r hello_app/requirements.txt
    
  displayName: 'Install dependencies'



- script: |
    
    pytest tests --cov=hello_app --cov-report=xml
  displayName: 'Run tests with coverage'


- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage.xml'

- task: ArchiveFiles@2
  condition: succeeded()
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(python.version).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
